steps:
- name: 'docker/compose:1.23.2'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/homepage:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/homepage:$COMMIT_SHA']
